# Generated by Django 4.1 on 2023-01-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_events_price_alter_events_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('age', models.FloatField()),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=75)),
                ('postalcode', models.FloatField()),
                ('avatar', models.ImageField(upload_to='')),
            ],
        ),
    ]
