# Generated by Django 4.1 on 2023-01-19 13:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_userinformation_user_alter_userinformation_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInformation',
            new_name='PrivetInformation',
        ),
    ]
