# Generated by Django 4.1 on 2023-01-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_userinformation_privetinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='privetinformation',
            name='email',
            field=models.EmailField(default='example@domain.com', max_length=254),
        ),
    ]
